{% set name = "db-dtypes" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db-dtypes-{{ version }}.tar.gz
  sha256: a5a5ab2105a5c854e5be0eeab7d83e49176f461d6f5c6cd22c0f6aeedd5a9166

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging >=17.0
    - pandas >=0.24.2,<2.0dev
    - pyarrow >=3.0.0
    - numpy >=1.16.6,<2.0dev

test:
  imports:
    - db_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  doc_url: https://googleapis.dev/python/db-dtypes/latest/index.html
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
