{% set name = "db-dtypes" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/db-dtypes-{{ version }}.tar.gz
  sha256: ab485c85fef2454f3182427def0b0a3ab179b2871542787d33ba519d62078883

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - packaging >=17.0
    - pandas >=0.24.2
    - pyarrow >=3.0.0
    - numpy >=1.16.6

test:
  imports:
    - db_dtypes
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-db-dtypes-pandas
  doc_url: https://googleapis.dev/python/db-dtypes/latest/index.html
  summary: Pandas Data Types for SQL systems (BigQuery, Spanner)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - tswast
